name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages] 

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.3.0

      - name: Install dependencies
        run: poetry install

      - id: deployment
        uses: sphinx-notes/pages@v3
